name: UPDATE-DIARY

on:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

env:
    TELEGRAM: ${{ secrets.TELEGRAM }}
    CHAT_ID: ${{ secrets.CHAT_ID }}

jobs:
  UPDATE-DIARY:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main

      - name: Update diary
        shell: powershell
        run:  |
          ./SCRIPTS/DIARY.ps1
